<?php

/**
 * @category   IntegerNet
 * @package    IntergerNet_Haendlerbund
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 * @author     Soeren Zorn <sz@integer-net.de>
 */

/**
 * @see IntegerNet_Haendlerbund_Block_Haendlerbund_System_Config_InsertLegislativeTexts
 */
?>
<script type="text/javascript">
//<![CDATA[

    var haendlerbundForm = Class.create();
    // inherit from Person class:
    haendlerbundForm.prototype = Object.extend(new varienForm('config_edit_form'), {
        // redefine the submit method
        _submit : function(){
            $(this.formId).request({
                onFailure: function() {
                    alert('Übertragungsfehler!');
                },
                onSuccess: function(t) {
                    new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
                        onFailure: function() {
                            alert('Übertragungsfehler!');
                        },
                        onSuccess: function(response) {
                            result = 'Übertragungsfehler: Die Rechtstexte konnten nicht eingetragen werden.';
                            try {
                                response = response.responseText;
                                if (response == 1) {
                                    result = 'Die Rechtstexte wurden erfolgreich übernommen.';
                                    $('haendlerbund_result').update(result);
                                    elem.removeClassName('fail').addClassName('success');
                                } else {
                                    elem.removeClassName('success').addClassName('fail');
                                }
                            } catch (e) {
                                elem.removeClassName('success').addClassName('fail');
                                $('haendlerbund_result').update(result);
                            }
                        }
                    });

                }
            });
        }
    });

    var legislativeForm = new haendlerbundForm('config_edit_form');
//]]>
</script>
<button onclick="legislativeForm.submit();" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span id="validation_result"><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
<div id="haendlerbund_result"></div>
